module VerifyExamples.List.Bag.Count2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import List.Bag exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#count: \n\n    count \"🍎\" []\n    --> 0" <|
        \() ->
            Expect.equal
                (
                count "🍎" []
                )
                (
                0
                )