module VerifyExamples.List.Bag.Intersection3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import List.Bag exposing (..)







spec3 : Test.Test
spec3 =
    Test.test "#intersection: \n\n    intersection [] [ ( \"🍇\", 1 ), ( \"🍎\", 1 ), ( \"🍊\", 1 ) ]\n    --> []" <|
        \() ->
            Expect.equal
                (
                intersection [] [ ( "🍇", 1 ), ( "🍎", 1 ), ( "🍊", 1 ) ]
                )
                (
                []
                )