module VerifyExamples.List.Bag.IsEmpty0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import List.Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#isEmpty: \n\n    isEmpty [(\"🍎\",42)]\n    --> False" <|
        \() ->
            Expect.equal
                (
                isEmpty [("🍎",42)]
                )
                (
                False
                )