module VerifyExamples.List.Bag.Minus0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import List.Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#minus: \n\n    minus [ ( \"🍎\", 2 ), ( \"🍊\", 1 ) ] [ ( \"🍇\", 2 ), ( \"🍎\", 2 ), ( \"🍊\", 2 ) ]\n    --> [(\"🍇\",2),(\"🍊\",1)]" <|
        \() ->
            Expect.equal
                (
                minus [ ( "🍎", 2 ), ( "🍊", 1 ) ] [ ( "🍇", 2 ), ( "🍎", 2 ), ( "🍊", 2 ) ]
                )
                (
                [("🍇",2),("🍊",1)]
                )