module VerifyExamples.List.Bag.Minus2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import List.Bag exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#minus: \n\n    minus [] [ ( \"🍇\", 1 ), ( \"🍎\", 1 ), ( \"🍊\", 1 ) ]\n    --> [(\"🍇\",1),(\"🍎\",1),(\"🍊\",1)]" <|
        \() ->
            Expect.equal
                (
                minus [] [ ( "🍇", 1 ), ( "🍎", 1 ), ( "🍊", 1 ) ]
                )
                (
                [("🍇",1),("🍎",1),("🍊",1)]
                )