module VerifyExamples.List.Bag.ToList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import List.Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toList: \n\n    toList [(\"🍊\",1),(\"🍎\",2),(\"🍇\",1)]\n    --> [\"🍊\",\"🍎\",\"🍎\",\"🍇\"]" <|
        \() ->
            Expect.equal
                (
                toList [("🍊",1),("🍎",2),("🍇",1)]
                )
                (
                ["🍊","🍎","🍎","🍇"]
                )