module VerifyExamples.List.Bag.ToList2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import List.Bag exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#toList: \n\n    toList []\n    --> []" <|
        \() ->
            Expect.equal
                (
                toList []
                )
                (
                []
                )