module VerifyExamples.Bag.FromList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#fromList: \n\n    [ \"🍇\", \"🍎\", \"🍊\", \"🍎\", \"🍊\", \"🍎\" ]\n        |> fromList identity\n        |> toAssociationList\n    --> [(\"🍇\",1),(\"🍊\",2),(\"🍎\",3)]" <|
        \() ->
            Expect.equal
                (
                [ "🍇", "🍎", "🍊", "🍎", "🍊", "🍎" ]
                    |> fromList identity
                    |> toAssociationList
                )
                (
                [("🍇",1),("🍊",2),("🍎",3)]
                )