module VerifyExamples.Bag.FromList2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#fromList: \n\n    [ \"🍎\", \"🍎\" ]\n        |> fromList identity\n        |> toAssociationList\n    --> [(\"🍎\",2)]" <|
        \() ->
            Expect.equal
                (
                [ "🍎", "🍎" ]
                    |> fromList identity
                    |> toAssociationList
                )
                (
                [("🍎",2)]
                )