module VerifyExamples.Bag.Insert0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#insert: \n\n    [ ( \"🍊\", 1 ), ( \"🍇\", 1 ) ]\n        |> fromAssociationList identity\n        |> insert 1 \"🍎\"\n        |> toAssociationList\n    --> [(\"🍇\",1),(\"🍊\",1),(\"🍎\",1)]" <|
        \() ->
            Expect.equal
                (
                [ ( "🍊", 1 ), ( "🍇", 1 ) ]
                    |> fromAssociationList identity
                    |> insert 1 "🍎"
                    |> toAssociationList
                )
                (
                [("🍇",1),("🍊",1),("🍎",1)]
                )