module VerifyExamples.Bag.Insert1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#insert: \n\n    [ ( \"🍊\", 1 ), ( \"🍎\", 1 ), ( \"🍇\", 1 ) ]\n        |> fromAssociationList identity\n        |> insert 2 \"🍎\"\n        |> toAssociationList\n    --> [(\"🍇\",1),(\"🍊\",1),(\"🍎\",3)]" <|
        \() ->
            Expect.equal
                (
                [ ( "🍊", 1 ), ( "🍎", 1 ), ( "🍇", 1 ) ]
                    |> fromAssociationList identity
                    |> insert 2 "🍎"
                    |> toAssociationList
                )
                (
                [("🍇",1),("🍊",1),("🍎",3)]
                )