module VerifyExamples.Bag.Insert2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#insert: \n\n    empty identity\n        |> insert 1 \"🍎\"\n        |> toAssociationList\n    --> [(\"🍎\",1)]" <|
        \() ->
            Expect.equal
                (
                empty identity
                    |> insert 1 "🍎"
                    |> toAssociationList
                )
                (
                [("🍎",1)]
                )