module VerifyExamples.Bag.Intersection2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#intersection: \n\n    empty identity\n        |> intersection (\n            [ ( \"🍇\", 1 ), ( \"🍎\", 1 ), ( \"🍊\", 1 ) ]\n                |> fromAssociationList identity\n        )\n        |> toAssociationList\n    --> []" <|
        \() ->
            Expect.equal
                (
                empty identity
                    |> intersection (
                        [ ( "🍇", 1 ), ( "🍎", 1 ), ( "🍊", 1 ) ]
                            |> fromAssociationList identity
                    )
                    |> toAssociationList
                )
                (
                []
                )