module VerifyExamples.Bag.Intersection1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#intersection: \n\n    [ ( \"🍎\", 1 ), ( \"🍊\", 1 ) ]\n        |> fromAssociationList identity\n        |> intersection (\n            [ ( \"🍇\", 1 ), ( \"🍎\", 1 ) ]\n                |> fromAssociationList identity\n        )\n        |> toAssociationList\n    --> [(\"🍎\",1)]" <|
        \() ->
            Expect.equal
                (
                [ ( "🍎", 1 ), ( "🍊", 1 ) ]
                    |> fromAssociationList identity
                    |> intersection (
                        [ ( "🍇", 1 ), ( "🍎", 1 ) ]
                            |> fromAssociationList identity
                    )
                    |> toAssociationList
                )
                (
                [("🍎",1)]
                )