module VerifyExamples.Bag.Intersection0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#intersection: \n\n    [ ( \"🍇\", 1 ), ( \"🍎\", 2 ), ( \"🍊\", 3 ) ]\n        |> fromAssociationList identity\n        |> intersection (\n            [ ( \"🍊\", 1 ), ( \"🍎\", 2 ), ( \"🍇\", 3 ) ]\n                |> fromAssociationList identity\n        )\n        |> toAssociationList\n    --> [(\"🍇\",1),(\"🍊\",1),(\"🍎\",2)]" <|
        \() ->
            Expect.equal
                (
                [ ( "🍇", 1 ), ( "🍎", 2 ), ( "🍊", 3 ) ]
                    |> fromAssociationList identity
                    |> intersection (
                        [ ( "🍊", 1 ), ( "🍎", 2 ), ( "🍇", 3 ) ]
                            |> fromAssociationList identity
                    )
                    |> toAssociationList
                )
                (
                [("🍇",1),("🍊",1),("🍎",2)]
                )