module VerifyExamples.Bag.IsEmpty0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#isEmpty: \n\n    singleton identity \"🍎\"\n        |> isEmpty\n    --> False" <|
        \() ->
            Expect.equal
                (
                singleton identity "🍎"
                    |> isEmpty
                )
                (
                False
                )