module VerifyExamples.Bag.IsEmpty1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#isEmpty: \n\n    empty identity\n        |> isEmpty\n    --> True" <|
        \() ->
            Expect.equal
                (
                empty identity
                    |> isEmpty
                )
                (
                True
                )