module VerifyExamples.Bag.Member2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#member: \n\n    member \"🍎\" (empty identity)\n    --> False" <|
        \() ->
            Expect.equal
                (
                member "🍎" (empty identity)
                )
                (
                False
                )