module VerifyExamples.Bag.Minus1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#minus: \n\n    empty identity\n        |> minus (\n            [ ( \"🍇\", 1 ), ( \"🍎\", 1 ), ( \"🍊\", 1 ) ]\n                |> fromAssociationList identity\n        )\n        |> toAssociationList\n    --> []" <|
        \() ->
            Expect.equal
                (
                empty identity
                    |> minus (
                        [ ( "🍇", 1 ), ( "🍎", 1 ), ( "🍊", 1 ) ]
                            |> fromAssociationList identity
                    )
                    |> toAssociationList
                )
                (
                []
                )