module VerifyExamples.Bag.Plus1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#plus: \n\n    [ ( \"🍇\", 1 ), ( \"🍎\", 1 ), ( \"🍊\", 1 ) ]\n        |> fromAssociationList identity\n        |> plus (singleton identity \"🍎\")\n        |> toAssociationList\n    --> [(\"🍇\",1),(\"🍊\",1),(\"🍎\",2)]" <|
        \() ->
            Expect.equal
                (
                [ ( "🍇", 1 ), ( "🍎", 1 ), ( "🍊", 1 ) ]
                    |> fromAssociationList identity
                    |> plus (singleton identity "🍎")
                    |> toAssociationList
                )
                (
                [("🍇",1),("🍊",1),("🍎",2)]
                )