module VerifyExamples.Bag.Remove3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec3 : Test.Test
spec3 =
    Test.test "#remove: \n\n    empty identity\n        |> remove 1 \"🍎\"\n        |> toAssociationList\n    --> []" <|
        \() ->
            Expect.equal
                (
                empty identity
                    |> remove 1 "🍎"
                    |> toAssociationList
                )
                (
                []
                )