module VerifyExamples.Bag.Remove1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#remove: \n\n    [ ( \"🍊\", 1 ), ( \"🍇\", 1 ) ]\n        |> fromAssociationList identity\n        |> remove 1 \"🍎\"\n        |> toAssociationList\n    --> [(\"🍇\",1),(\"🍊\",1)]" <|
        \() ->
            Expect.equal
                (
                [ ( "🍊", 1 ), ( "🍇", 1 ) ]
                    |> fromAssociationList identity
                    |> remove 1 "🍎"
                    |> toAssociationList
                )
                (
                [("🍇",1),("🍊",1)]
                )