module VerifyExamples.Bag.Singleton0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#singleton: \n\n    singleton identity \"🍎\" |> toAssociationList\n    --> [ ( \"🍎\", 1 ) ]" <|
        \() ->
            Expect.equal
                (
                singleton identity "🍎" |> toAssociationList
                )
                (
                [ ( "🍎", 1 ) ]
                )