module VerifyExamples.Bag.ToList0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bag exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toList: \n\n    [ ( \"🍊\", 1 ), ( \"🍎\", 2 ), ( \"🍇\", 1 ) ]\n        |> fromAssociationList identity\n        |> toList\n    --> [\"🍇\",\"🍊\",\"🍎\",\"🍎\"]" <|
        \() ->
            Expect.equal
                (
                [ ( "🍊", 1 ), ( "🍎", 2 ), ( "🍇", 1 ) ]
                    |> fromAssociationList identity
                    |> toList
                )
                (
                ["🍇","🍊","🍎","🍎"]
                )